module.exports = {
    'antd-button.md': require('./antd-button.md'),
    'antd-icon.md': require('./antd-icon.md'),
    'antd-grid.md': require('./antd-grid.md'),
    'antd-layout.md': require('./antd-layout.md'),

    'antd-auto-complete.md': require('./antd-auto-complete.md'),
    'antd-cascader.md': require('./antd-cascader.md'),
    'antd-checkbox.md': require('./antd-checkbox.md'),
    'antd-date-picker.md': require('./antd-date-picker.md'),
    'antd-input-number.md': require('./antd-input-number.md'),
    'antd-input.md': require('./antd-input.md'),
    'antd-radio.md': require('./antd-radio.md'),
    'antd-rate.md': require('./antd-rate.md'),
    'antd-select.md': require('./antd-select.md'),
    'antd-switch.md': require('./antd-switch.md'),
    'antd-upload.md': require('./antd-upload.md'),

    'antd-avatar.md': require('./antd-avatar.md'),
    'antd-badge.md': require('./antd-badge.md'),
    'antd-calendar.md': require('./antd-calendar.md'),
    'antd-card.md': require('./antd-card.md'),
    'antd-carousel.md': require('./antd-carousel.md'),
    'antd-collapse.md': require('./antd-collapse.md'),
    'antd-popover.md': require('./antd-popover.md'),
    'antd-tooltip.md': require('./antd-tooltip.md'),
    'antd-tabs.md': require('./antd-tabs.md'),
    'antd-tag.md': require('./antd-tag.md'),
    'antd-timeline.md': require('./antd-timeline.md'),

    'antd-affix.md': require('./antd-affix.md'),
    'antd-breadcrumb.md': require('./antd-breadcrumb.md'),
    'antd-dropdown.md': require('./antd-dropdown.md'),
    'antd-menu.md': require('./antd-menu.md'),
    'antd-pagination.md': require('./antd-pagination.md'),
    'antd-steps.md': require('./antd-steps.md'),

    'antd-alert.md': require('./antd-alert.md'),
    'antd-message.md': require('./antd-message.md'),
    'antd-notification.md': require('./antd-notification.md'),
    'antd-progress.md': require('./antd-progress.md'),
    'antd-popconfirm.md': require('./antd-popconfirm.md'),
    'antd-loading.md': require('./antd-loading.md'),

    'antd-anchor.md': require('./antd-anchor.md'),
    'antd-backtop.md': require('./antd-backtop.md')
};